### ISSUE TITLE
BAV_CLASS

### ISSUE THREAD

**Issue by victor-nakajima** [wppbav/bavapi-sdk-python#11]
I would like to share a code from a former coworker that implemented some functions.
But this space don't allow .py file, could you help me with this issue?

**Comment by nachomaiz** [comment]
Hi @victor-nakajima, thank you for reaching out.

Sounds interesting! What does the code that you want to share do?

Let me know if you are a WPP employee, we can move this conversation to email.

Thanks!

**Comment by victor-nakajima** [comment]
Hi Nacho!
Yes, I from vmlyr brazil, here my email for you: victor.nakajima@vmlyr.com

**Comment by nachomaiz** [comment]
Sounds good, will reach out on Monday!
